services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    build:
      context: pipeline
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  
    networks:
      - net

  remote_host:
    container_name: remote_host
    image: remote_host
    build:
      context: ./fedora
    networks:
      - net

  db_data:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - $PWD/db_data:/var/lib/mysql
    networks:
      - net

  web:
      container_name: web
      image: ansible-web
      build:
        context: jenkins-ansible/web
      ports:
        - "80:80"
      networks:
        - net

  git:
      image: gitlab/gitlab-ce:latest
      container_name: git-server
      hostname: 'gitlab.example.com'
      ports:
        - '8090:80'
      volumes:
        - $PWD/srv/gitlab/config:/etc/gitlab
        - $PWD/srv/gitlab/logs:/var/log/gitlab
        - $PWD/srv/gitlab/data:/var/opt/gitlab
      networks:
        - net      
networks:
  net:


